import random


def FUNCTION(students: list[str]):
    with open("assignment7.output", "tw", encoding="utf8") as f:
        for name in students:
            n = random.randrange(3, 20)
            grades = [random.randrange(1, 11) for i in range(n)]
            grades_s = ", ".join(map(str, grades))
            avg = sum(grades) / len(grades)

            f.write(f"Student {name}: {n} grades\n{grades_s}\nAverage: {avg}\n\n")


FUNCTION(
    [
        "Horace Hauck",
        "Gerald Greenfelder",
        "Jeffrey Damore",
        "Adrain Anderson",
        "Alek Watsica",
        "Percy Collier",
        "Jarrod Schultz",
        "Vada Schmitt",
        "Courtney Lang",
        "Taryn Lemke",
        "Erick Sipes",
        "Mohammad Schroeder",
        "Elvis Tremblay",
        "Grayce Kunze",
        "Gladyce Thiel",
        "Chaya Langworth",
        "Roberta Buckridge",
        "Selena Kautzer",
        "Leilani Olson",
        "Jensen Torphy",
        "Kylee Hilll",
        "Brandt Waelchi",
        "Una Konopelski",
        "Trudie Lemke",
        "Keith Mann",
        "Vance Bailey",
        "Henderson Renner",
        "Sammie Wolff",
        "Schuyler Rohan",
        "Gianni Steuber",
        "Lamont Ruecker",
        "Mya Goodwin",
        "Weston Ortiz",
        "Juwan Daugherty",
        "Ebony Koepp",
        "Alene Rau",
        "Claud Goyette",
        "Elda Daniel",
        "Euna Stamm",
        "Angelo Grady",
        "Luisa Herzog",
        "Michale Eichmann",
        "Elza Goyette",
        "Casimir Weber",
        "Owen Nienow",
        "Janick Waelchi",
        "Hassie White",
        "Celestine Greenfelder",
        "Athena Trantow",
        "Marcella Johnston",
        "Ryder Jaskolski",
        "Clementine Marvin",
        "Jordan Langworth",
        "Wilfred Stracke",
        "Dayne Larkin",
        "Jesse Kuphal",
        "Filiberto Kuhn",
        "Linda Johnston",
        "Kiera Cronin",
        "Pinkie Daugherty",
        "Lamont Marvin",
        "Dedrick Douglas",
        "Hailey Mills",
        "Noelia Stark",
        "Merlin Gutmann",
        "Alene Beahan",
        "Sid Hammes",
        "Floy Bashirian",
        "Liliana Herman",
        "Otilia Jast",
        "Murl Hermann",
        "Ollie Hahn",
        "Angeline Reichert",
        "Kiarra Weber",
        "Lulu Breitenberg",
        "Harmon Koch",
        "Johnnie Price",
        "Bonnie Schmeler",
        "Ola Leannon",
        "Leopoldo Lindgren",
        "Bart Schumm",
        "Wilford Sauer",
        "Jaycee Goyette",
        "Gene Ortiz",
        "Ariel Yost",
        "Clint Kub",
        "Kip Abbott",
        "Carole Lubowitz",
        "Jensen McLaughlin",
        "Kody Reichel",
        "Ivah Rice",
        "Lacey Reichel",
        "Tracey Hoppe",
        "Earline Lueilwitz",
        "Lester Goyette",
        "Casimir Little",
        "Blake Schmeler",
        "Brennan Kovacek",
        "Gus Schmidt",
        "Meaghan Buckridge",
    ]
)
